name: Docker BuildX Image CI

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout source
        uses: actions/checkout@v2
      -
        name: Set Environment Variables
        run: |
          echo "VERSION=$(find * -maxdepth 1 -type d -name '1.*' | sort -V | tail -n 1)" >> $GITHUB_ENV
          echo "PLATFORM=linux/amd64,linux/arm64" >> $GITHUB_ENV
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
        with:
          platforms: amd64,arm64

      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to Dockerhub
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: ${{ env.VERSION }}
          platforms: ${{ env.PLATFORM }}
          push: true
          pull: true
          cache-from: type=gha
          cache-to: type=gha,mode=max
          tags: |
              ghcr.io/owenthereal/unbound-docker:${{ env.VERSION }}
              ghcr.io/owenthereal/unbound-docker:latest
